/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ber_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1001c81e16b724b3584b5301c462885d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/bootstrap/ber_b.h>
// pydoc.h is automatically generated in the build directory
#include <ber_b_pydoc.h>

void bind_ber_b(py::module& m)
{

    using ber_b    = gr::bootstrap::ber_b;


    py::class_<ber_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ber_b>>(m, "ber_b", D(ber_b))

        .def(py::init(&ber_b::make),
           D(ber_b,make)
        )
        



        ;




}








